#管道入口
ducts:
  - 1.5,-58,1.5

#维修处
fixes:
  - 5.5,-59,5.5

#电梯坐标 电梯门坐标（从上到下为游戏里从下到上）
lifts:
  - 4,-59.3,16
    3,-58,14
    3,-55,14
    3,-52,14

#可拾取物品
# x y z 数量 类名
items:
  - 2 -60 13 256
    ChamberStandardCartridge
  - 2 -60 13 1
    gun.ChamberPistol
    gun.ChamberShotgun
    gun.CabinGuardian